//
//  PlayLog.swift
//  medo-delirio-api
//
//  Created by Rafael Claycon Schmitt on 06/10/26.
//

import Fluent
import Vapor

/// One play of a sound or song in the app, sent in daily batches by installs that opted in
/// to sharing their trends.
///
/// A burst of re-taps on the same content is folded into a single play by the app before
/// it gets here; the rule lives in `PlayDeduplicator` on the client, which is why every row
/// carries the app version that counted it.
final class PlayLog: Model {

    static let schema = "PlayLog"

    /// Generated by the app, not here, so a batch that is sent twice is stored once.
    @ID(key: .id)
    var id: UUID?

    @Field(key: "installId")
    var installId: String

    @Field(key: "contentId")
    var contentId: String

    /// `ContentType` raw value, taken from `MedoContent` rather than trusted from the app.
    @Field(key: "contentType")
    var contentType: Int

    /// ISO 8601 with fractional seconds, as the app recorded it, like `ShareCountStat`.
    @Field(key: "dateTime")
    var dateTime: String

    /// Started by a playlist advancing on its own rather than by a tap.
    @Field(key: "isAutoplay")
    var isAutoplay: Bool

    @Field(key: "appVersion")
    var appVersion: String

    init() { }

    init(
        id: UUID,
        installId: String,
        contentId: String,
        contentType: Int,
        dateTime: String,
        isAutoplay: Bool,
        appVersion: String
    ) {
        self.id = id
        self.installId = installId
        self.contentId = contentId
        self.contentType = contentType
        self.dateTime = dateTime
        self.isAutoplay = isAutoplay
        self.appVersion = appVersion
    }
}
